from uuid import uuid4

from app.models import Company, MergeCompaniesRequest, MergeCompaniesResponse
from app.repository import SqliteRepository


class MergeService:
    def __init__(self, repo: SqliteRepository) -> None:
        self.repo = repo

    # Merge companies method that utilized the repository/DAO to perform the necessary database operations to merge two companies together and send a response.
    async def merge_companies(self, request: MergeCompaniesRequest) -> MergeCompaniesResponse:
        # Validate the request before attempting to merge.
        await self.validate_merge_request(request)

        # Create a new Company object from the data in the request.
        merged_company = self.build_merged_company(request)

        # Add the new Company object to the database.
        await self.repo.insert_company(merged_company)

        # Store the source company ids in a list for easy passing to the repository methods.
        source_company_ids = [request.source_company_1_id, request.source_company_2_id]

        # Reassign users and branches from the source companies to the new merged company, then mark the source companies as deleted in the database.
        await self.repo.reassign_users(source_company_ids, merged_company.id)
        await self.repo.reassign_branches(source_company_ids, merged_company.id)
        await self.repo.soft_delete_companies(source_company_ids)

        # Send back a response to the frontend.
        return MergeCompaniesResponse(
            merged_company_id=merged_company.id,
            source_company_1_id=request.source_company_1_id,
            source_company_2_id=request.source_company_2_id,
            status="accepted",
        )

    # Checks that source companies exist and that the request is valid before attempting to merge.
    async def validate_merge_request(self, request: MergeCompaniesRequest) -> None:
        raise NotImplementedError("TODO: validate source companies exist and request is sane")

    def build_merged_company(self, request: MergeCompaniesRequest) -> Company:
        # New id is generated by backend, not trusted from client.
        return Company(
            id=str(uuid4()),
            name=request.resolved_company.name,
            address=request.resolved_company.address,
            credit_limit=request.resolved_company.credit_limit,
            is_deleted=False,
        )
